services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AZURE_SQL_SERVER=""
      - AZURE_SQL_DATABASE=""
      - AZURE_SQL_USERNAME=""
      - AZURE_SQL_PASSWORD=""
      - AZURE_SQL_DRIVER=ODBC Driver 17 for SQL Server
    volumes:
      - ./api:/app
    networks:
      - radical_k9_network
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - API_URL=http://api:8000
      - SECRET_KEY=clave-secreta-radical-k9
    volumes:
      - ./frontend:/app
    depends_on:
      - api
    networks:
      - radical_k9_network

networks:
  radical_k9_network: